name: Continuous Integration Tests

on:
  pull_request:
    branches: [ main ]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true  

jobs:
  ci:
    name: Continuous Integration Tests
    timeout-minutes: 30
    services:
      clickhouse:
        image: clickhouse/clickhouse-server:22.3
        ports:
          - 9000:9000
          - 8123:8123
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: wait for services to start up
        run: sleep 10
      - name: dbt version
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt --version
      - name: dbt debug
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt debug          
      - name: dbt deps
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt deps
      - name: dbt init_source_data 
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt run-operation init_source_data
      - name: dbt build
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt build --full-refresh
      - name: cube api
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: curl -H "Authorization:token" -G --data-urlencode 'query={"measures":["f_tracker.bounces"]}' http://cube:4000/cubejs-api/v1/load  
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ failure() }}
      #   timeout-minutes: 30
        